### ISSUE TITLE
Create General Technical Documentation (NRI)

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hub/ACCESS-Hub#22]
As a user I need some information about how to use GitHub to be able to contribute to ACCESSHub and potentially ACCESS-NRI supported repositories. As a user I value quality information that I know  comes from a trusted source.

As maintainer of ACCESSHub I need a site that provides general information on how to use GitHub that I can link to on ACCESSHub. This should be an NRI produced and supported repository to ensure a high quality of information consistent with NRI requirements.

**Comment by ccarouge** [comment]
A preference for a repo name? Should we go for a specific repo for How To or a generic "Training" repository?

**Comment by aidanheerdegen** [comment]
The decision making part of my brain is exhausted. Either would be fine, and can be changed later. How about a "How To" section of a "Training" repo?

(going for maximum consensus)

**Comment by ccarouge** [comment]
Adding content for #2
