### ISSUE TITLE
Instructions on modifying

### ISSUE THREAD

**Issue by AndyHoggANU** [ACCESS-Hub/ACCESS-Hub#24]
Just to note that my experience at trying an "Edit directly on github" was different to the instructions. 
For me, it created a fork which meant I didn't have the option to commit directly to github.
I think this is because I don't have admin privileges (which will be the case in general).
Maybe these instructions need to cover both eventualities?

**Comment by aidanheerdegen** [comment]
I believe this is also the reason the preview doesn't work

https://github.com/ACCESS-NRI-Community/ACCESSHub/pull/23#issuecomment-1238755540

Can we use you as a guinea pig @AndyHoggANU and test what we need to do to get this functioning for non-owners?

**Comment by AndyHoggANU** [comment]
Yep, go for it, just send me instructions

**Comment by aidanheerdegen** [comment]
I have made a "Reviewers" team and added you. Sorry to waste your time, but I don't think this will work, but I just want to check that is the case before I try adding you to the a team with write access which should do the trick.

**Comment by aidanheerdegen** [comment]
Can you try the same process you did before (I presume hitting the "edit" button on the site)? This means creating a new PR I am afraid.

**Comment by AndyHoggANU** [comment]
Tried again. Still didn't see the same view as the instructions (no option to edit directly).

**Comment by aidanheerdegen** [comment]
Yep. I saw. I've added you to the Contributors team which has write access. Can you try reloading and see if there is an edit button?

**Comment by AndyHoggANU** [comment]
No edit button but I could merge even though the check failed?

**Comment by AndyHoggANU** [comment]
Managed to re-run the check - still failed.

**Comment by aidanheerdegen** [comment]
I can see the edit button from a private browser window (so not logged into GitHub)
![Screen Shot 2022-09-07 at 11 14 11 am](https://user-images.githubusercontent.com/6063709/188767268-587949e4-0ba8-4c52-a534-b3303250fc26.png)

**Comment by AndyHoggANU** [comment]
Aah, OK, I see. 
I had done this differently -- by going through github, navigating to `index.md` and then clicking the pen within github. If you do that, the interface is quite different.

When I do it your way, the checks pass!

**Comment by aidanheerdegen** [comment]
@ccarouge Can you clarify, do the instructions intend to use the edit button on the rendered site or in the GitHub repository?

**Comment by ccarouge** [comment]
On the rendered site definitely.

**Comment by ccarouge** [comment]
I see how to make the text clearer. For example, putting a link with "go to the ACCESSHub site" or simply say "on this site" since they are reading the instructions on the site they need to be. Or both.

**Comment by aidanheerdegen** [comment]
Could use the graphic above, or something similar.

**Comment by ccarouge** [comment]
Highlight not to use level 1 headers in pages because they aren't picked up in the page toc.

**Comment by ccarouge** [comment]
Add request to join the GitHub organisation to the How to contribute.
