### ISSUE TITLE
Add Partner logos/links (as footer if an option)

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hub/ACCESS-Hub#49]

**Comment by rbeucher** [comment]
Partners organisations:

- ANU
- Bureau of Meteorology
- CSIRO
- Monash University
- The University of Melbourne
- UNSW
- University of Tasmania

**Comment by rbeucher** [comment]
Partners organisations:

- ANU
- Bureau of Meteorology
- CSIRO
- Monash University
- The University of Melbourne
- UNSW
- University of Tasmania

**Comment by rbeucher** [comment]
![image.png](https://images.zenhubusercontent.com/62fb2cbe712f1c3c56159fdb/4551d30d-578b-414e-b5c3-ca90d75b4243)

**Comment by ccarouge** [comment]
It looks nice but I don't know if we want the copyright there in the community site.

**Comment by ccarouge** [comment]
Do we need NCRIS?

**Comment by rbeucher** [comment]
I think we need NCRIS yes.

@kdruken, @aidanheerdegen  What do you think?

**Comment by ccarouge** [comment]
Get the social links to work from the mkdocs.yml. 

No copyright for community site.

For ACCESS-NRI Hub, add the CC-BY 4.0 icon to the copyright.
