### ISSUE TITLE
Add social links to footer?

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hub/ACCESS-Hub#63]

**Comment by ccarouge** [comment]
For the footer, I saw this: 
https://squidfunk.github.io/mkdocs-material/upgrade/#changes-to-html-files

I wonder if we could use this structure to retain the setting of the copyright and social links via `mkdocs.yml` while still personalising the footer.

**Comment by rbeucher** [comment]
Yes, I thought about that but it's too much of a pain I think.

**Comment by rbeucher** [comment]
I'll have a look. I agree it would be good to retain the settings in the `mkdocs.yml`

**Comment by rbeucher** [comment]
OK It's easy and much better, thanks for pointing that out!
