### ISSUE TITLE
Add Copyright Information in footer

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hub/ACCESS-Hub#64]

**Comment by ccarouge** [comment]
Don't work on that one yet. There are some changes. See #44

**Comment by rbeucher** [comment]
I was just gonna add "Copyright 2022 - ACCESS-NRI"

**Comment by ccarouge** [comment]
Except I've added "Licensed under CC-BY 4.0 2022 by ACCESS-NRI" And for the Community one, I'm not sure if we'll want anything.

**Comment by rbeucher** [comment]
Could be a CC logo with a link to the licence if you want.
