### ISSUE TITLE
Search bar has disappeared

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hub/ACCESS-Hub#78]
The search bar seems to have disappeared from the headers of both "sites".

**Comment by ccarouge** [comment]
The addition of the git-revision-date-localized plugin caused this. Looking to see why it is happening.

**Comment by ccarouge** [comment]
Found the cause in the Material for Mkdocs documentation:
> The built-in search plugin integrates seamlessly with Material for MkDocs, adding multilingual client-side search with [lunr](https://lunrjs.com/) and [lunr-languages](https://github.com/MihaiValentin/lunr-languages). It's enabled by default, but must be re-added to mkdocs.yml when other plugins are used

We need to specify the search plugin because we have added another plugin. I'll put this together with a PR for another ticket.

**Comment by ccarouge** [comment]
Closed by #67
