### ISSUE TITLE
Fix deadlinks

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-Hub/ACCESS-Hub#84]
Added CI to [check for deadlinks][deadlinks] as found a few, need to clean those.

[deadlinks]: https://github.com/ACCESS-Hub/ACCESS-Hub/actions/runs/3086767646/jobs/4991458234

**Comment by ccarouge** [comment]
How to contribute guide refers to http://127.0.0.1:8000 to give the location of the local preview. This will not exist but needs to be here. Need to whitelist this link from the CI.

**Comment by ccarouge** [comment]
This is flagged as a deadlink: `../contribution_setup/#install-material-for-mkdocs-not-required` but it actually works in the documentation. I'll disable the check for the links to sections on other pages.

**Comment by ccarouge** [comment]
Some links are flagged as dead because they return codes [403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) and 401. Should we whitelist these codes in the config file @rbeucher ?

**Comment by rbeucher** [comment]
yes go for it

**Comment by ccarouge** [comment]
Closed by #85
